- platform: template
  sensors:
    garatentor_status:
      device_class: garage_door
      friendly_name: "Garagentor"
      value_template: "{% if is_state('binary_sensor.garagentor_external_input', 'on') %}
        on
      {% else %}
        off
      {% endif %}"
      icon_template: >-
        {% if is_state('binary_sensor.garagentor_external_input', 'on') %}
          mdi:garage-open-variant
        {% else %}
          mdi:garage-variant
        {% endif %}

    last_day_of_the_month:
      friendly_name: 'Letzer Tag des Monats'
      icon_template: "mdi:calendar"
      value_template: "{{ (now() + timedelta(days=1)).day == 1 }}"
      unique_id: c3966e047e2e445db0236003d9a1f5d0

- platform: tod
  name: Morgen
  after: sunrise
  after_offset: "-02:00"
  before: "12:00"
- platform: tod
  name: Mittag
  after: "12:00"
  before: "17:00"
- platform: tod
  name: Abend
  after: "17:00"
  before: "22:00"
- platform: tod
  name: Nacht
  after: "22:00"
  before: sunrise