- platform: xiaomi_cloud_map_extractor
  host: !secret xiaomi_vacuum_host
  token: !secret xiaomi_vacuum_token
  username: !secret xiaomi_cloud_username
  password: !secret xiaomi_cloud_password
  draw: ['all']
  attributes:
    - calibration_points
    - rooms
  country: "de"
#- platform: mjpeg
#  name: ESPCam
#  mjpeg_url: "http://192.168.178.98:81/stream"
#  still_image_url: "http://192.168.178.98/capture"