# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
fontawesome:

# Text to speech
tts:
  - platform: google_translate
    language: "de"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensoren.yaml
switch: !include switch.yaml
template: !include template.yaml
panel_iframe: !include panel_iframe.yaml

homeassistant:
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/card-mod.js

powercalc:

#Selbsterstellte Includes
waste_collection_schedule: !include waste_collection.yaml
binary_sensor: !include binary_sensor.yaml
cover: !include cover.yaml
light: !include light.yaml
notify: !include notify.yaml
mqtt: !include mqtt.yaml
homekit: !include homekit.yaml
#camera: !include camera.yaml
#rest: !include rest.yaml

#Stuff zur Alexa bringen was in HA ist.
emulated_hue:
  host_ip: 192.168.178.53
  listen_port: 80
  entities:
    light.licht_rechts:
      name: "Licht rechts"
    light.licht_links:
      name: "Licht links"
    light.licht_schuppen:
      name: "Licht Schuppen"
    light.dreamview_t1:
      name: "Ambilight"
    light.mittagapuse_joshua:
      name: "Mittagspause Joshua"

#Telegram Bot Settings
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 406580581

#calendar:
#  - platform: caldav
#    username: !secret icloud_login
#    password: !secret icloud_password
#    url: !secret icloud_url
#    calendars:
#      - "Familie"

#Settings für NGINX Proxy Manager
http:
  use_x_forwarded_for: true
  trusted_proxies:
    #NPM IP-Adresse
    - 192.168.178.5
    #cloudflare ipv4
    - 173.245.48.0/20
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.93.240.0/20
    - 188.114.96.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 162.158.0.0/15
    - 104.16.0.0/13
    - 104.24.0.0/14
    - 172.64.0.0/13
    - 131.0.72.0/22
    #cloudflare ipv6
    - 2400:cb00::/32
    - 2606:4700::/32
    - 2803:f800::/32
    - 2405:b500::/32
    - 2405:8100::/32
    - 2a06:98c0::/29
    - 2c0f:f248::/32
    #IPs im Log
    - 198.41.242.198
    - 198.41.242.250
    - 172.70.242.152
    - 172.70.251.85
    - 172.70.251.29
  ip_ban_enabled: true
  login_attempts_threshold: 5

#History Daten nurnoch in MySQL Server
recorder:
#  db_url: mysql://homeassistant:homeassistant@192.168.178.2:3306/homeassistant?charset=utf8
#MariaDB Addon
  db_url: mysql://homeassistant:homeassistant@core-mariadb/homeassistant?charset=utf8mb4
  exclude:
    entities:
      - sensor.rewe_865799