#Erstellen von Shelly Add-On als Garagentor für HK Integration
- platform: template
  covers:
    garage_door:
      device_class: garage
      friendly_name: "Garagentor"
      value_template: >-
        {% if is_state('binary_sensor.garagentor_external_input','on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garagentor
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garagentor
      stop_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garagentor
      icon_template: >-
        {% if is_state('binary_sensor.garagentor_external_input','on') %}
          mdi:garage-open-variant
        {% else %}
          mdi:garage-variant
        {% endif %}

##Vorbereitung für neue Steuerung
#- platform: template
#  covers:
#    garage_door:
#      device_class: garage
#      friendly_name: "Garagentor"
#      value_template: >-
#        {% if is_state('binary_sensor.garagentor_external_input','on') %}
#          Open
#        {% endif %}
#        {% if is_state('NEUERSENSOR','off') %}
#          Closed
#        {% endif %}
#      open_cover:
#        service: switch.turn_on
#        data:
#          entity_id: switch.garagentor
#      close_cover:
#        service: switch.turn_on
#        data:
#          entity_id: switch.garagentor
#      stop_cover:
#        service: switch.turn_on
#        data:
#          entity_id: switch.garagentor
#      icon_template: >-
#        {% if is_state('binary_sensor.garagentor_external_input','on') %}
#          mdi:garage-open-variant
#        {% endif %}
#        {% if is_state('NEUERSENSOR','off') %}
#          mdi:garage-variant
#        {% endif %}