- platform: switch
  name: Licht rechts
  entity_id: switch.licht_rechts
- platform: switch
  name: Licht links
  entity_id: switch.licht_links
- platform: switch
  name: Licht Schuppen
  entity_id: switch.schuppen
- platform: switch
  name: Mittagspause Joshua
  entity_id: switch.mittagspause_joshi
- platform: template
  lights:
    weihnachtsbaum_kerzen:
      friendly_name: "Weihnachtsbaumkerzen"
      turn_on:
        service: script.weihnachtsbaum_kerzen_an
      turn_off:
        service: script.weihnachtsbaum_kerzen_aus
      icon_template: mdi:candle
      unique_id: 1ae016b2bdcc4b488c1f4bbbd03432d4